### ISSUE TITLE
 [Symfony\Component\Debug\Exception\FatalErrorException]              Class 'GionniValeriana\LaravelAdminlteServiceProvider' not found  

### ISSUE THREAD

**Issue by camgrsl** [gionnivaleriana/laravel-adminlte#1]
I had that error while running the composer require 

 [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'GionniValeriana\LaravelAdminlteServiceProvider' not found  

Full statck:

 quigo  sudo composer require gionnivaleriana/laravel-adminlte:dev-master
Password:
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'GionniValeriana\LaravelAdminlteServiceProvider' not found  

Script php artisan clear-compiled handling the post-update-cmd event returned with an error

  [RuntimeException]  
  Error Output:       

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [packages1] ... [packagesN]

**Comment by fjbardelli** [comment]
The same error, de pakage not work

**Comment by lenh** [comment]
I am having the same issue - this package does not seem to work nor is the documentation very detailed.

**Comment by int2k** [comment]
try this
in provider section
use 
`'GionniValeriana\laravelAdminlte\AdminlteServiceProvider',`
instead of 
`'GionniValeriana\LaravelAdminlteServiceProvider',`

in aliases use 
`'Adminlte' => 'GionniValeriana\laravelAdminlte\Adminlte',`
instead of  
`'Adminlte' => 'GionniValeriana\laraveladminlte',`

**Comment by joylazari** [comment]
You're right @int2k, my bad.
Doc fixed in f50260a7cc
